In [1]:
import numpy as np
squareArr = np.arange(1,10)

In [2]:
squareArr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
squareArr = squareArr.reshape(3,3)
squareArr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
squareArr[1,1:2]

array([5])

In [19]:
randomRow = np.random.random((10,1))
randomRow

array([[ 0.26777505],
       [ 0.76582796],
       [ 0.17359052],
       [ 0.11522671],
       [ 0.34223513],
       [ 0.4200245 ],
       [ 0.85338942],
       [ 0.1019294 ],
       [ 0.21192255],
       [ 0.29159326]])

In [20]:
fibIndices = np.array([1, 1, 2, 3])

In [21]:
randomRow[fibIndices]

array([[ 0.76582796],
       [ 0.76582796],
       [ 0.17359052],
       [ 0.11522671]])

In [25]:
boolIndices = np.array([ [True, False, True], [True, False, False], [True, False, True]])

In [28]:
squareArr[boolIndices]

array([1, 3, 4, 7, 9])

In [29]:
np.average(squareArr)

5.0

In [30]:
np.median(squareArr)

5.0

In [31]:
np.sum(squareArr)

45

In [32]:
# Sum all rows column 0
np.sum(squareArr[:,0])

12

In [34]:
# Compare operations between arrays, boolean result per element
sqAvg = np.average(squareArr)
betterThanAverage = squareArr > sqAvg
betterThanAverage

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]], dtype=bool)

In [39]:
stddev = np.std(squareArr)
stddev

2.5819888974716112

In [41]:
# Pass by reference example
fred = squareArr
fred[1,1] = 0
fred

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [42]:
squareArr

array([[1, 2, 3],
       [4, 0, 6],
       [7, 8, 9]])

In [43]:
fred[1,1]=5

In [45]:
fred = squareArr.copy()

In [46]:
clampedSqArr = np.array(squareArr.copy(), dtype=float)
clampedSqArr[ (squareArr - sqAvg) > stddev] = sqAvg + stddev
clampedSqArr

array([[ 1.       ,  2.       ,  3.       ],
       [ 4.       ,  5.       ,  6.       ],
       [ 7.       ,  7.5819889,  7.5819889]])

In [47]:
squareArr * 2

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [48]:
squareArr + np.ones( (3,3) )

array([[  2.,   3.,   4.],
       [  5.,   6.,   7.],
       [  8.,   9.,  10.]])

In [49]:
squareArr + 1

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [50]:
squareArr * np.arange(1,10).reshape( (3,3) )

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [53]:
matA = np.array( [[1,2],[3,4]])
matB = np.array( [[5,6],[7,8]])
np.dot(matA, matB)

array([[19, 22],
       [43, 50]])